import type { TabItem } from "@/src/components/common/TopTabs";
import type { SelectOption } from "@/src/components/admin/releases/releaseFormOptions";
import type { CheckoutStepKey, Invoice, PaymentGatewayOption, Plan } from "./types";

export const CHECKOUT_STEP_TABS: TabItem<CheckoutStepKey>[] = [
  { key: "plan", label: "Choose Plan" },
  { key: "details", label: "Details" },
  { key: "checkout", label: "Checkout" },
];

export const MOCK_PLANS: Plan[] = [
  {
    id: "free",
    name: "Free",
    icon: "music",
    highlighted: false,
    tagline: "Try the platform with limited uploads",
    priceMonthly: 0,
    priceSuffix: "",
    features: [
      { label: "Up to 3 releases per year", included: true },
      { label: "All major streaming platforms", included: true },
      { label: "Basic analytics dashboard", included: true },
      { label: "Standard moderation queue", included: true },
      { label: "Unlimited releases", included: false },
      { label: "Priority moderation", included: false },
      { label: "Advanced analytics", included: false },
    ],
    ctaLabel: "Current Plan",
    ctaDisabled: true,
    billingCycle: "YEARLY",
    currency: "USD",
    isCurrentPlan: false,
    isFree: true,
  },
  {
    id: "pro",
    name: "Pro",
    icon: "zap",
    highlighted: true,
    tagline: "For artists ready to grow their audience",
    priceMonthly: 7.99,
    priceSuffix: "/mo",
    billedAsLabel: "Billed as $95.88/year",
    discountBadge: "-20%",
    features: [
      { label: "Unlimited releases", included: true },
      { label: "All major streaming platforms", included: true },
      { label: "Advanced analytics & insights", included: true },
      { label: "Priority moderation (faster approval)", included: true },
      { label: "SoundCloud & Tidal distribution", included: true },
      { label: "Early access to new features", included: true },
      { label: "Dedicated artist support", included: true },
    ],
    ctaLabel: "Upgrade - $7.99/mo",
    billingCycle: "MONTHLY",
    currency: "USD",
    isCurrentPlan: false,
    isFree: false,
  },
  {
    id: "label",
    name: "Label",
    icon: "building",
    highlighted: false,
    tagline: "For independent labels and serious artists who want full control",
    priceMonthly: 19,
    priceSuffix: "/mo",
    billedAsLabel: "Billed as $182.88/year",
    discountBadge: "-20%",
    features: [
      { label: "Unlimited releases", included: true },
      { label: "Unlimited artists under one subscription", included: true },
      {
        label: "Distribution to all major streaming platforms",
        included: true,
      },
      { label: "Distribution to Beatport and other DJ stores", included: true },
      { label: "Quarterly detailed reporting", included: true },
      { label: "Advanced analytics & insights", included: true },
      { label: "Priority moderation (fastest approval)", included: true },
      { label: "Early access to new features", included: true },
      { label: "Priority customer support", included: true },
    ],
    ctaLabel: "Choose Label - $19/mo",
    billingCycle: "MONTHLY",
    currency: "USD",
    isCurrentPlan: false,
    isFree: false,
  },
  {
    id: "pay-per-release",
    name: "Pay Per Release",
    icon: "coin",
    highlighted: false,
    tagline: "For artists who upload occasionally",
    priceMonthly: 2.99,
    priceSuffix: "/release",
    features: [
      { label: "No monthly fee", included: true },
      { label: "All major platforms", included: true },
      { label: "Pay only when you release", included: true },
      { label: "No long-term commitment", included: true },
      { label: "Unlimited releases", included: false },
      { label: "Priority moderation", included: false },
    ],
    ctaLabel: "Choose Pay Per Release",
    billingCycle: "PER_RELEASE",
    currency: "USD",
    isCurrentPlan: false,
    isFree: false,
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv-2024-03",
    planName: "Free Plan",
    invoiceNumber: "INV-2024-03",
    date: "Dec 1, 2024",
    amount: 0,
    isFree: true,
  },
  {
    id: "inv-2024-02",
    planName: "Free Plan",
    invoiceNumber: "INV-2024-02",
    date: "Nov 1, 2024",
    amount: 0,
    isFree: true,
  },
  {
    id: "inv-2024-01",
    planName: "Free Plan",
    invoiceNumber: "INV-2024-01",
    date: "Oct 1, 2024",
    amount: 0,
    isFree: true,
  },
];

export const PAYMENT_GATEWAYS: PaymentGatewayOption[] = [
  {
    id: "gateway-paypal",
    gateway: "PAYPAL",
    label: "PayPal",
    description: "Pay with your PayPal account.",
    isDefault: true,
  },
  {
    id: "gateway-cloudpayments",
    gateway: "CLOUDPAYMENTS",
    label: "CloudPayments",
    description: "Pay securely with your card.",
    isDefault: false,
  },
];

export const COUNTRY_OPTIONS: SelectOption[] = [
  { value: "af", label: "Afghanistan" },
  { value: "ax", label: "Aland Islands" },
  { value: "al", label: "Albania" },
  { value: "dz", label: "Algeria" },
  { value: "as", label: "American Samoa" },
  { value: "ad", label: "Andorra" },
  { value: "ao", label: "Angola" },
  { value: "ai", label: "Anguilla" },
  { value: "aq", label: "Antarctica" },
  { value: "ag", label: "Antigua and Barbuda" },
  { value: "ar", label: "Argentina" },
  { value: "am", label: "Armenia" },
  { value: "aw", label: "Aruba" },
  { value: "au", label: "Australia" },
  { value: "at", label: "Austria" },
  { value: "az", label: "Azerbaijan" },

  { value: "bs", label: "Bahamas" },
  { value: "bh", label: "Bahrain" },
  { value: "bd", label: "Bangladesh" },
  { value: "bb", label: "Barbados" },
  { value: "by", label: "Belarus" },
  { value: "be", label: "Belgium" },
  { value: "bz", label: "Belize" },
  { value: "bj", label: "Benin" },
  { value: "bm", label: "Bermuda" },
  { value: "bt", label: "Bhutan" },
  { value: "bo", label: "Bolivia" },
  { value: "bq", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "ba", label: "Bosnia and Herzegovina" },
  { value: "bw", label: "Botswana" },
  { value: "bv", label: "Bouvet Island" },
  { value: "br", label: "Brazil" },
  { value: "io", label: "British Indian Ocean Territory" },
  { value: "bn", label: "Brunei" },
  { value: "bg", label: "Bulgaria" },
  { value: "bf", label: "Burkina Faso" },
  { value: "bi", label: "Burundi" },

  { value: "cv", label: "Cabo Verde" },
  { value: "kh", label: "Cambodia" },
  { value: "cm", label: "Cameroon" },
  { value: "ca", label: "Canada" },
  { value: "ky", label: "Cayman Islands" },
  { value: "cf", label: "Central African Republic" },
  { value: "td", label: "Chad" },
  { value: "cl", label: "Chile" },
  { value: "cn", label: "China" },
  { value: "cx", label: "Christmas Island" },
  { value: "cc", label: "Cocos Islands" },
  { value: "co", label: "Colombia" },
  { value: "km", label: "Comoros" },
  { value: "cg", label: "Congo" },
  { value: "cd", label: "Congo, Democratic Republic of the" },
  { value: "ck", label: "Cook Islands" },
  { value: "cr", label: "Costa Rica" },
  { value: "ci", label: "Cote d'Ivoire" },
  { value: "hr", label: "Croatia" },
  { value: "cu", label: "Cuba" },
  { value: "cw", label: "Curacao" },
  { value: "cy", label: "Cyprus" },
  { value: "cz", label: "Czechia" },

  { value: "dk", label: "Denmark" },
  { value: "dj", label: "Djibouti" },
  { value: "dm", label: "Dominica" },
  { value: "do", label: "Dominican Republic" },

  { value: "ec", label: "Ecuador" },
  { value: "eg", label: "Egypt" },
  { value: "sv", label: "El Salvador" },
  { value: "gq", label: "Equatorial Guinea" },
  { value: "er", label: "Eritrea" },
  { value: "ee", label: "Estonia" },
  { value: "sz", label: "Eswatini" },
  { value: "et", label: "Ethiopia" },

  { value: "fk", label: "Falkland Islands" },
  { value: "fo", label: "Faroe Islands" },
  { value: "fj", label: "Fiji" },
  { value: "fi", label: "Finland" },
  { value: "fr", label: "France" },
  { value: "gf", label: "French Guiana" },
  { value: "pf", label: "French Polynesia" },
  { value: "tf", label: "French Southern Territories" },

  { value: "ga", label: "Gabon" },
  { value: "gm", label: "Gambia" },
  { value: "ge", label: "Georgia" },
  { value: "de", label: "Germany" },
  { value: "gh", label: "Ghana" },
  { value: "gi", label: "Gibraltar" },
  { value: "gr", label: "Greece" },
  { value: "gl", label: "Greenland" },
  { value: "gd", label: "Grenada" },
  { value: "gp", label: "Guadeloupe" },
  { value: "gu", label: "Guam" },
  { value: "gt", label: "Guatemala" },
  { value: "gg", label: "Guernsey" },
  { value: "gn", label: "Guinea" },
  { value: "gw", label: "Guinea-Bissau" },
  { value: "gy", label: "Guyana" },

  { value: "ht", label: "Haiti" },
  { value: "hm", label: "Heard Island and McDonald Islands" },
  { value: "va", label: "Vatican City" },
  { value: "hn", label: "Honduras" },
  { value: "hk", label: "Hong Kong" },
  { value: "hu", label: "Hungary" },

  { value: "is", label: "Iceland" },
  { value: "in", label: "India" },
  { value: "id", label: "Indonesia" },
  { value: "ir", label: "Iran" },
  { value: "iq", label: "Iraq" },
  { value: "ie", label: "Ireland" },
  { value: "im", label: "Isle of Man" },
  { value: "il", label: "Israel" },
  { value: "it", label: "Italy" },

  { value: "jm", label: "Jamaica" },
  { value: "jp", label: "Japan" },
  { value: "je", label: "Jersey" },
  { value: "jo", label: "Jordan" },

  { value: "kz", label: "Kazakhstan" },
  { value: "ke", label: "Kenya" },
  { value: "ki", label: "Kiribati" },
  { value: "kp", label: "North Korea" },
  { value: "kr", label: "South Korea" },
  { value: "kw", label: "Kuwait" },
  { value: "kg", label: "Kyrgyzstan" },

  { value: "la", label: "Laos" },
  { value: "lv", label: "Latvia" },
  { value: "lb", label: "Lebanon" },
  { value: "ls", label: "Lesotho" },
  { value: "lr", label: "Liberia" },
  { value: "ly", label: "Libya" },
  { value: "li", label: "Liechtenstein" },
  { value: "lt", label: "Lithuania" },
  { value: "lu", label: "Luxembourg" },

  { value: "mo", label: "Macao" },
  { value: "mg", label: "Madagascar" },
  { value: "mw", label: "Malawi" },
  { value: "my", label: "Malaysia" },
  { value: "mv", label: "Maldives" },
  { value: "ml", label: "Mali" },
  { value: "mt", label: "Malta" },
  { value: "mh", label: "Marshall Islands" },
  { value: "mq", label: "Martinique" },
  { value: "mr", label: "Mauritania" },
  { value: "mu", label: "Mauritius" },
  { value: "yt", label: "Mayotte" },
  { value: "mx", label: "Mexico" },
  { value: "fm", label: "Micronesia" },
  { value: "md", label: "Moldova" },
  { value: "mc", label: "Monaco" },
  { value: "mn", label: "Mongolia" },
  { value: "me", label: "Montenegro" },
  { value: "ms", label: "Montserrat" },
  { value: "ma", label: "Morocco" },
  { value: "mz", label: "Mozambique" },
  { value: "mm", label: "Myanmar" },

  { value: "na", label: "Namibia" },
  { value: "nr", label: "Nauru" },
  { value: "np", label: "Nepal" },
  { value: "nl", label: "Netherlands" },
  { value: "nc", label: "New Caledonia" },
  { value: "nz", label: "New Zealand" },
  { value: "ni", label: "Nicaragua" },
  { value: "ne", label: "Niger" },
  { value: "ng", label: "Nigeria" },
  { value: "nu", label: "Niue" },
  { value: "nf", label: "Norfolk Island" },
  { value: "mk", label: "North Macedonia" },
  { value: "mp", label: "Northern Mariana Islands" },
  { value: "no", label: "Norway" },

  { value: "om", label: "Oman" },

  { value: "pk", label: "Pakistan" },
  { value: "pw", label: "Palau" },
  { value: "ps", label: "Palestine" },
  { value: "pa", label: "Panama" },
  { value: "pg", label: "Papua New Guinea" },
  { value: "py", label: "Paraguay" },
  { value: "pe", label: "Peru" },
  { value: "ph", label: "Philippines" },
  { value: "pn", label: "Pitcairn" },
  { value: "pl", label: "Poland" },
  { value: "pt", label: "Portugal" },
  { value: "pr", label: "Puerto Rico" },

  { value: "qa", label: "Qatar" },

  { value: "re", label: "Réunion" },
  { value: "ro", label: "Romania" },
  { value: "ru", label: "Russia" },
  { value: "rw", label: "Rwanda" },

  { value: "bl", label: "Saint Barthélemy" },
  { value: "sh", label: "Saint Helena" },
  { value: "kn", label: "Saint Kitts and Nevis" },
  { value: "lc", label: "Saint Lucia" },
  { value: "mf", label: "Saint Martin" },
  { value: "pm", label: "Saint Pierre and Miquelon" },
  { value: "vc", label: "Saint Vincent and the Grenadines" },
  { value: "ws", label: "Samoa" },
  { value: "sm", label: "San Marino" },
  { value: "st", label: "Sao Tome and Principe" },
  { value: "sa", label: "Saudi Arabia" },
  { value: "sn", label: "Senegal" },
  { value: "rs", label: "Serbia" },
  { value: "sc", label: "Seychelles" },
  { value: "sl", label: "Sierra Leone" },
  { value: "sg", label: "Singapore" },
  { value: "sx", label: "Sint Maarten" },
  { value: "sk", label: "Slovakia" },
  { value: "si", label: "Slovenia" },
  { value: "sb", label: "Solomon Islands" },
  { value: "so", label: "Somalia" },
  { value: "za", label: "South Africa" },
  { value: "gs", label: "South Georgia and the South Sandwich Islands" },
  { value: "ss", label: "South Sudan" },
  { value: "es", label: "Spain" },
  { value: "lk", label: "Sri Lanka" },
  { value: "sd", label: "Sudan" },
  { value: "sr", label: "Suriname" },
  { value: "sj", label: "Svalbard and Jan Mayen" },
  { value: "se", label: "Sweden" },
  { value: "ch", label: "Switzerland" },
  { value: "sy", label: "Syria" },

  { value: "tw", label: "Taiwan" },
  { value: "tj", label: "Tajikistan" },
  { value: "tz", label: "Tanzania" },
  { value: "th", label: "Thailand" },
  { value: "tl", label: "Timor-Leste" },
  { value: "tg", label: "Togo" },
  { value: "tk", label: "Tokelau" },
  { value: "to", label: "Tonga" },
  { value: "tt", label: "Trinidad and Tobago" },
  { value: "tn", label: "Tunisia" },
  { value: "tr", label: "Turkey" },
  { value: "tm", label: "Turkmenistan" },
  { value: "tc", label: "Turks and Caicos Islands" },
  { value: "tv", label: "Tuvalu" },

  { value: "ug", label: "Uganda" },
  { value: "ua", label: "Ukraine" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "gb", label: "United Kingdom" },
  { value: "us", label: "United States" },
  { value: "um", label: "United States Minor Outlying Islands" },
  { value: "uy", label: "Uruguay" },
  { value: "uz", label: "Uzbekistan" },

  { value: "vu", label: "Vanuatu" },
  { value: "ve", label: "Venezuela" },
  { value: "vn", label: "Vietnam" },
  { value: "vg", label: "British Virgin Islands" },
  { value: "vi", label: "U.S. Virgin Islands" },

  { value: "wf", label: "Wallis and Futuna" },
  { value: "eh", label: "Western Sahara" },

  { value: "ye", label: "Yemen" },

  { value: "zm", label: "Zambia" },
  { value: "zw", label: "Zimbabwe" },
];
