import type { DispatcherDetailsRecord } from "./dispatcherDetailsTypes";

const carrierDocuments = [
    {
        id: "carrier-contract",
        label: "Carrier Contract",
        fileName: "Carrier Contract.pdf",
        meta: "0.87 MB · Mar 23, 2026, 09:06 PM",
        required: true,
    },
    {
        id: "certificate-insurance",
        label: "Certificate of Insurance",
        fileName: "Certificate of Insurance.pdf",
        meta: "0.87 MB · Mar 23, 2026, 09:06 PM",
        required: true,
    },
    {
        id: "limited-power",
        label: "Limited Power of Attorney",
        fileName: "Limited_Power_of_Attorney.pdf",
        meta: "0.87 MB · Mar 23, 2026, 09:06 PM",
        required: true,
    },
    {
        id: "mc-authority",
        label: "MC Authority",
        fileName: "MC_Authority.pdf",
        meta: "0.87 MB · Mar 23, 2026, 09:06 PM",
        required: true,
    },
    {
        id: "notice-assignment",
        label: "Notice of Assignment",
        fileName: "Notice_of_Assignment.pdf",
        meta: "0.87 MB · Mar 23, 2026, 09:06 PM",
        required: true,
    },
    {
        id: "void-check",
        label: "Void Check",
        fileName: "Void_Check.pdf",
        meta: "0.87 MB · Mar 23, 2026, 09:06 PM",
        required: true,
    },
    {
        id: "w9",
        label: "W-9",
        fileName: "Carrier Contract.pdf",
        meta: "0.87 MB · Mar 23, 2026, 09:06 PM",
    },
    {
        id: "trucker-intake",
        label: "Trucker Intake Survey",
        fileName: "Trucker_Intake_Survey.pdf",
        meta: "0.87 MB · Mar 23, 2026, 09:06 PM",
    },
];

const loadRows = Array.from({ length: 7 }, (_, index) => ({
    id: `load-${index + 1}`,
    loadNumber: "LD-2024-001",
    dateRange: "2024-03-01 - 2024-03-03",
    route: "Dallas, TX - Chicago, IL",
    assignedTo: "Kathryn Murphy",
    assignedToPhone: "(34245)",
    carrier: "ABC Transport Inc.",
    dispatchFeePercentage: "10%",
    miles: "247",
    dispatcherEarning: "$860",
    revenue: "$2,500",
}));

export const dispatcherDetailsRecords: DispatcherDetailsRecord[] = [
    {
        id: "02",
        name: "James Clark",
        role: "Senior Dispatcher",
        email: "yourmail@gmail.com",
        phone: "+1 (555) 243-9021",
        address: "Dallas, TX",
        status: "Active",
        avatarUrl: "/images/dispatchers/my_photo.jpg",
        joinedAt: "12 February, 2026",
        totalCarriers: 8,
        totalCompletedLoads: 10,
        totalMiles: "5466",
        totalRevenue: "$1,250,700",
        totalDispatcherRevenue: "$10,700",
        carriers: [
            {
                id: "02",
                initials: "JM",
                name: "Mason Delta LTD",
                dbaName: "Mason Delta LTD",
                mcNumber: "24234",
                dotNumber: "112321",
                pricingPlan: "Basic Plan",
                contact: "+32 123423",
                address: "4234 Mustang GT",
                createdAt: "2026-04-12",
                email: "delta@gmail.com",
                phone: "+1 (555) 018-4421",
                activeLoads: 4,
                totalRevenue: "$82,400",
                documents: carrierDocuments,
            },
            {
                id: "03",
                initials: "JM",
                name: "Truck Inc",
                dbaName: "Truck Inc",
                mcNumber: "24234",
                dotNumber: "112321",
                pricingPlan: "Basic Plan",
                contact: "+32 123423",
                address: "4234 Mustang GT",
                createdAt: "2026-04-11",
                email: "ops@northlinefreight.com",
                phone: "+1 (555) 018-7632",
                activeLoads: 3,
                totalRevenue: "$64,800",
                documents: carrierDocuments,
            },
            {
                id: "04",
                initials: "JM",
                name: "Alpha LTD",
                dbaName: "Alpha LTD",
                mcNumber: "24234",
                dotNumber: "112321",
                pricingPlan: "Basic Plan",
                contact: "+32 123423",
                address: "4234 Mustang GT",
                createdAt: "2026-04-10",
                email: "alpha@example.com",
                phone: "+1 (555) 018-5521",
                activeLoads: 2,
                totalRevenue: "$44,200",
                documents: carrierDocuments,
            },
            {
                id: "05",
                initials: "JM",
                name: "Truck Inc",
                dbaName: "Truck Inc",
                mcNumber: "24234",
                dotNumber: "112321",
                pricingPlan: "Basic Plan",
                contact: "+32 123423",
                address: "4234 Mustang GT",
                createdAt: "2026-04-09",
                email: "truck@example.com",
                phone: "+1 (555) 018-9912",
                activeLoads: 1,
                totalRevenue: "$38,700",
                documents: carrierDocuments,
            },
        ],
        loads: loadRows,
    },
    ...["03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13"].map(
        (id) => ({
            id,
            name: "Dispatcher Profile",
            role: "Dispatcher",
            email: "yourmail@gmail.com",
            phone: "+1 (555) 243-9021",
            address: "Dallas, TX",
            status: id === "05" || id === "07" || id === "10" || id === "13" ? "Suspended" as const : "Active" as const,
            avatarUrl: "/images/dispatchers/my_photo.jpg",
            joinedAt: "12 February, 2026",
            totalCarriers: 4,
            totalCompletedLoads: 10,
            totalMiles: "5466",
            totalRevenue: "$1,250,700",
            totalDispatcherRevenue: "$10,700",
            carriers: [
                {
                    id: "02",
                    initials: "JM",
                    name: "Mason Delta LTD",
                    dbaName: "Mason Delta LTD",
                    mcNumber: "24234",
                    dotNumber: "112321",
                    pricingPlan: "Basic Plan",
                    contact: "+32 123423",
                    address: "4234 Mustang GT",
                    createdAt: "2026-04-12",
                    email: "dispatch@abctransport.com",
                    phone: "+1 (555) 018-4421",
                    activeLoads: 4,
                    totalRevenue: "$82,400",
                    documents: carrierDocuments,
                },
            ],
            loads: loadRows,
        }),
    ),
];

export function getDispatcherDetailsById(dispatcherId: string) {
    return dispatcherDetailsRecords.find((dispatcher) => dispatcher.id === dispatcherId)
        ?? dispatcherDetailsRecords[0];
}
